// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
function supabaseAsUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthedResult() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}
function jsonResult(data, structuredContent) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: structuredContent ?? { data }
  };
}

// src/lib/mcp/tools/list-items.ts
var list_items_default = defineTool({
  name: "list_items",
  title: "List inventory items",
  description: "List all items in the master product catalog (name, category, unit).",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to filter item names.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    let query = supabase.from("items").select("id, name, category, unit_of_measure").order("name");
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-daily-stock.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_daily_stock_default = defineTool2({
  name: "list_daily_stock_sheets",
  title: "List daily stock sheet entries",
  description: "List daily stock sheet entries. RLS restricts results to the caller's assigned teams (admins see all).",
  inputSchema: {
    start_date: z2.string().optional().describe("Filter entries on or after this ISO date (YYYY-MM-DD)."),
    end_date: z2.string().optional().describe("Filter entries on or before this ISO date (YYYY-MM-DD)."),
    team_member: z2.string().optional().describe("Filter by retail team member name."),
    limit: z2.number().int().positive().max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, team_member, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    let query = supabase.from("daily_stock_sheets").select("id, date, retail_team_name, item_id, open_qty, qty_in, close_qty, sales_qty, reach, os_status, remark, items(name, unit_of_measure)").order("date", { ascending: false }).limit(limit);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (team_member) query = query.eq("retail_team_name", team_member);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-issuance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_issuance_default = defineTool3({
  name: "list_issuance",
  title: "List issuance ledger",
  description: "List items issued to recipient groups (Retail, Housekeeping, Managers, Cube, Bar).",
  inputSchema: {
    start_date: z3.string().optional(),
    end_date: z3.string().optional(),
    recipient_group: z3.string().optional(),
    limit: z3.number().int().positive().max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, recipient_group, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    let query = supabase.from("issuance_ledger").select("id, date, recipient_group, item_id, quantity, issued_by, items(name, unit_of_measure)").order("date", { ascending: false }).limit(limit);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (recipient_group) query = query.eq("recipient_group", recipient_group);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-transfers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_transfers_default = defineTool4({
  name: "list_transfers",
  title: "List transfer ledger",
  description: "List items transferred to other branches/businesses.",
  inputSchema: {
    start_date: z4.string().optional(),
    end_date: z4.string().optional(),
    destination: z4.string().optional(),
    limit: z4.number().int().positive().max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, destination, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    let query = supabase.from("transfer_ledger").select("id, date, destination, item_id, quantity, reason, items(name, unit_of_measure)").order("date", { ascending: false }).limit(limit);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (destination) query = query.eq("destination", destination);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-received.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_received_default = defineTool5({
  name: "list_received",
  title: "List received ledger",
  description: "List items received from suppliers.",
  inputSchema: {
    start_date: z5.string().optional(),
    end_date: z5.string().optional(),
    supplier: z5.string().optional(),
    limit: z5.number().int().positive().max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, supplier, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    let query = supabase.from("received_ledger").select("id, date, supplier, item_id, quantity, invoice_number, items(name, unit_of_measure)").order("date", { ascending: false }).limit(limit);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (supplier) query = query.ilike("supplier", `%${supplier}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-weekly-count.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
var list_weekly_count_default = defineTool6({
  name: "list_weekly_stock_counts",
  title: "List weekly stock counts",
  description: "List physical stock counts by location (Main Store, 24hr Store, Cube).",
  inputSchema: {
    start_date: z6.string().optional(),
    end_date: z6.string().optional(),
    location: z6.string().optional(),
    limit: z6.number().int().positive().max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, location, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    let query = supabase.from("weekly_stock_counts").select("id, date, location, item_id, physical_count, notes, items(name, unit_of_measure)").order("date", { ascending: false }).limit(limit);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (location) query = query.eq("location", location);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/record-issuance.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^4.4.3";
var record_issuance_default = defineTool7({
  name: "record_issuance",
  title: "Record an issuance",
  description: "Record items issued to a recipient group. Requires an existing item id.",
  inputSchema: {
    date: z7.string().describe("ISO date (YYYY-MM-DD)."),
    recipient_group: z7.enum(["Retail", "Housekeeping", "Managers", "Cube", "Bar"]).describe("Recipient group receiving the issuance."),
    item_id: z7.string().uuid().describe("Item id from list_items."),
    quantity: z7.number().positive()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ date, recipient_group, item_id, quantity }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    const issuedBy = ctx.getUserEmail() ?? ctx.getUserId() ?? "mcp";
    const { data, error } = await supabase.from("issuance_ledger").insert({ date, recipient_group, item_id, quantity, issued_by: issuedBy }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data, { row: data });
  }
});

// src/lib/mcp/tools/record-received.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^4.4.3";
var record_received_default = defineTool8({
  name: "record_received",
  title: "Record a receipt from a supplier",
  description: "Record items received from a supplier. Requires an existing item id.",
  inputSchema: {
    date: z8.string().describe("ISO date (YYYY-MM-DD)."),
    supplier: z8.string().min(1),
    item_id: z8.string().uuid(),
    quantity: z8.number().positive(),
    invoice_number: z8.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ date, supplier, item_id, quantity, invoice_number }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("received_ledger").insert({ date, supplier, item_id, quantity, invoice_number: invoice_number ?? null }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data, { row: data });
  }
});

// src/lib/mcp/tools/record-transfer.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^4.4.3";
var record_transfer_default = defineTool9({
  name: "record_transfer",
  title: "Record a transfer",
  description: "Record items transferred to another branch or business.",
  inputSchema: {
    date: z9.string().describe("ISO date (YYYY-MM-DD)."),
    destination: z9.string().min(1),
    item_id: z9.string().uuid(),
    quantity: z9.number().positive(),
    reason: z9.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ date, destination, item_id, quantity, reason }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthedResult();
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("transfer_ledger").insert({ date, destination, item_id, quantity, reason: reason ?? null }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data, { row: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "mqeqopnzopriuzckjjiz";
var mcp_default = defineMcp({
  name: "stockist-mcp",
  title: "Stockist MCP",
  version: "0.1.0",
  instructions: "Tools for the Stockist inventory app. Use list_* tools to inspect items, ledgers, and stock sheets. Use record_* tools to add new issuance, received, or transfer entries. All operations run as the signed-in user and respect team-based row-level security (non-admins only see data for their assigned retail teams).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_items_default,
    list_daily_stock_default,
    list_issuance_default,
    list_transfers_default,
    list_received_default,
    list_weekly_count_default,
    record_issuance_default,
    record_received_default,
    record_transfer_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
